# Generated by Django 6.0.5 on 2026-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('blog_type', models.CharField(max_length=100)),
                ('view_count', models.IntegerField()),
                ('blog_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='customerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('image', models.ImageField(upload_to='reviews/')),
                ('star_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField()),
                ('favicon', models.TextField()),
                ('last_news_image', models.ImageField(upload_to='site_settings/')),
                ('last_news_description', models.TextField()),
                ('tel_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('about_small_title', models.CharField(max_length=100)),
                ('about_big_title', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
                ('about_image', models.ImageField(upload_to='site_settings/')),
                ('about_count_first', models.IntegerField()),
                ('about_count_second', models.IntegerField()),
                ('about_count_third', models.IntegerField()),
                ('about_count_fourth', models.IntegerField()),
                ('about_count_first_title', models.TextField()),
                ('about_count_second_title', models.TextField()),
                ('about_count_third_title', models.TextField()),
                ('about_count_fourth_title', models.TextField()),
                ('our_mission_title', models.CharField(max_length=100)),
                ('our_mission_description', models.TextField()),
                ('our_view_title', models.CharField(max_length=100)),
                ('our_view_description', models.TextField()),
                ('our_values_title', models.CharField(max_length=100)),
                ('our_values_description', models.TextField()),
                ('contact_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
    ]
