# Generated by Django 6.0.5 on 2026-06-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner_description_az_banner_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerler'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Bloq', 'verbose_name_plural': 'Bloqlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə', 'verbose_name_plural': 'Əlaqələr'},
        ),
        migrations.AlterModelOptions(
            name='customerreview',
            options={'verbose_name': 'Müştəri Rəyi', 'verbose_name_plural': 'Müştəri Rəyleri'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Layihə', 'verbose_name_plural': 'Layihələr'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Ayar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosial Media', 'verbose_name_plural': 'Sosial Medialar'},
        ),
    ]
